// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywctoyorhyldkvehugqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3Y3RveW9yaHlsZGt2ZWh1Z3FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzOTIzMzcsImV4cCI6MjA1MDk2ODMzN30.Hdkf5MTXpLHF39Np7hHVrWpiuU1zVrPZyOc6eLhx6xE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);